# (Opsiyonal) Olist reviews' - Translations...

* 🇧🇷 Brezilya Portekizcesi bilmiyorsanız, hadi `order_reviews` metinlerini 🇬🇧 İngilizce’ye çevirelim!

* Bunun için `pip install googletrans==4.0.2` yüklemeniz gerekecek.

☢️ Bu API ile herhangi bir sorun yaşarsanız, bunu düzeltmek için zaman harcamayın, bu package oldukça dengesiz… Aklınızda bulunsun:
- bu optional bir challenge
- Brezilya Portekizcesi ile yazılmış review’ların anlamını görmek için bazı yorumları Google Translate’e kopyalayıp yapıştırarak yine de eski yöntemle yapabilirsiniz.

## Review Translator

👉 `reviews` dataset’ini load edin ve 1-yıldız rating’e sahip review’lardan bir örnek (sample) seçin.

In [1]:
#%pip install googletrans==4.0.2
#%pip install google-trans-new
%pip install argostranslate

Requirement already satisfied: argostranslate in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (1.10.0)
Requirement already satisfied: ctranslate2<5,>=4.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (4.6.2)
Requirement already satisfied: packaging in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (24.2)
Requirement already satisfied: sacremoses<0.2,>=0.0.53 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (0.1.1)
Requirement already satisfied: sentencepiece<0.3,>=0.2.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (0.2.0)
Requirement already satisfied: spacy in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (3.8.11)
Requirement already satisfied: stanza==1.10.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from argostranslate) (1.10.1)
Requirement already satisfied: emoji in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (2.15.0)
Requirement already satisfied: numpy in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (1.26.4)
Requirement already satisfied: protobuf>=3.15.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (4.25.6)
Requirement already satisfied: requests in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (2.32.3)
Requirement already satisfied: networkx in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (3.4.2)
Requirement already satisfied: torch>=1.3.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (2.6.0+cpu.cxx11.abi)
Requirement already satisfied: tqdm in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from stanza==1.10.1->argostranslate) (4.67.1)
Requirement already satisfied: setuptools in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from ctranslate2<5,>=4.0->argostranslate) (75.8.0)
Requirement already satisfied: pyyaml<7,>=5.3 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from ctranslate2<5,>=4.0->argostranslate) (6.0.2)
Requirement already satisfied: regex in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from sacremoses<0.2,>=0.0.53->argostranslate) (2024.11.6)
Requirement already satisfied: click in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from sacremoses<0.2,>=0.0.53->argostranslate) (8.1.8)
Requirement already satisfied: joblib in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from sacremoses<0.2,>=0.0.53->argostranslate) (1.4.2)
Requirement already satisfied: filelock in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from torch>=1.3.0->stanza==1.10.1->argostranslate) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from torch>=1.3.0->stanza==1.10.1->argostranslate) (4.12.2)
Requirement already satisfied: jinja2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from torch>=1.3.0->stanza==1.10.1->argostranslate) (3.1.5)
Requirement already satisfied: fsspec in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from torch>=1.3.0->stanza==1.10.1->argostranslate) (2025.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from torch>=1.3.0->stanza==1.10.1->argostranslate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.3.0->stanza==1.10.1->argostranslate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from jinja2->torch>=1.3.0->stanza==1.10.1->argostranslate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from requests->stanza==1.10.1->argostranslate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from requests->stanza==1.10.1->argostranslate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from requests->stanza==1.10.1->argostranslate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from requests->stanza==1.10.1->argostranslate) (2025.1.31)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (0.21.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from spacy->argostranslate) (2.10.6)
Requirement already satisfied: annotated-types>=0.6.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->argostranslate) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->argostranslate) (2.27.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy->argostranslate) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy->argostranslate) (0.1.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from weasel<0.5.0,>=0.4.2->spacy->argostranslate) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from weasel<0.5.0,>=0.4.2->spacy->argostranslate) (7.1.0)
Requirement already satisfied: wrapt in /home/zeynepdil/.pyenv/versions/workintech/lib/python3.12/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy->argostranslate) (1.17.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from pathlib import Path
#from google_trans_new import google_translator
#translator = google_translator()

import argostranslate.package as pkg
import argostranslate.translate as translate

In [3]:
pkg.update_package_index()
available = pkg.get_available_packages()

pt_en = [p for p in available if p.from_code == "pt" and p.to_code == "en"][0]
pkg.install_from_path(pt_en.download())

In [4]:
DATA_DIR = Path("/home/zeynepdil/code/data-orders/data")
# Verileri yükle
reviews = pd.read_csv(DATA_DIR / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(DATA_DIR / "olist_orders_dataset.csv")

In [23]:
# Verileri yükle
#from olist.data import Olist
#ata = Olist().get_data()

In [5]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [6]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

👀 20 adet düşük puan alan yorumdan oluşan bir örneklem seçin (rastgele) ve bunu bir listeye dönüştürün.

In [9]:
low_score_reviews = reviews[
    (reviews["review_score"] == 1) &
    (reviews["review_comment_message"].notna())
]

len(low_score_reviews)

8745

In [10]:
sample_20_reviews = low_score_reviews.sample(n=20, random_state=42) 
review_to_text = sample_20_reviews["review_comment_message"].tolist()

🗣 Bu göreve başlamadan önce önceden yüklediğiniz `google_translator` paketini kullanarak bu yorumları çevirin:

In [12]:
english_translated_reviews = []
for text in review_to_text:
    #try:
      translated = translate.translate(text, "pt", "en")
      english_translated_reviews.append(translated)
    #except Exception as e:
        #print("Error in translation: ", e)
english_translated_reviews[0]

'Product sent Unlike the one in the ad. I asked to return the product and receive the amount paid, but I still had no answer. I hope to resolve this unpleasant problem in a consensual way.'

In [13]:
translation_df = pd.DataFrame({
    "original_text": review_to_text,
    "translated_text": english_translated_reviews
})

print(translation_df)

                                        original_text  \
0   Foi enviado produto Diferente daquele do anúnc...
1   Não comprem desta loja! Tentei fazer o cancela...
2                                           Excelente
3   O jogo de bolas de bilhar que comprei é totalm...
4                        material ruim. sem garantia
5   Gostaria de saber por que o meu produto consta...
6   Olá queria informar que o produto não foi entr...
7   Já se passaram quase um mês e nada preciso da ...
8   Falta receber o protetor de porta e os jogos d...
9   Boa tarde. \r\nNão recebo todos os produtos fa...
10    Não estou satisfeita com a qualidade do produto
11  Minha mercadoria não foi entregue , já paguei ...
12                     Aparelho não funciona direito
13  A cor do produto no site é mais claro que o pr...
14  Nao gostei do produto. As toalhas sao muito fi...
15        Comprei duas unidades e recebi apenas uma!
16                          Produto não foi entregue
17  Não foi entregue o produto que solicitei. Entr...
18  Fiquei esperando o produto chegar e nada, most...
19  Difícil de resolver um problema na entrega. Co...

                                      translated_text
0   Product sent Unlike the one in the ad. I asked...
1   Don't buy from this store! I tried to cancel t...
2                                          Excellent.
3   The pool ball game I bought is totally differe...
4                                Bad stuff. unsecured
5   I'd like to know why my product appears as del...
6   Hello I wanted to inform you that the product ...
7   It's been almost a month and I don't need your...
8   Missing to receive door guard and single bed g...
9   Good afternoon.\nI don't get all the products....
10            I am not satisfied with product quality
11  My merchandise wasn't delivered, I already pai...
12                        Apparatus not working right
13  The color of the product on the site is cleare...
14  I don't like the product. The towels are very ...
15               I bought two units and got only one!
16                              Product not delivered
17  The product I requested was not delivered. I'v...
18  I kept waiting for the product to arrive and n...
19  Hard to solve a delivery problem. I bought 3 i...

In [14]:
only_translated = translation_df.dropna(subset = ["translated_text"])
print(only_translated)

                                        original_text  \
0   Foi enviado produto Diferente daquele do anúnc...
1   Não comprem desta loja! Tentei fazer o cancela...
2                                           Excelente
3   O jogo de bolas de bilhar que comprei é totalm...
4                        material ruim. sem garantia
5   Gostaria de saber por que o meu produto consta...
6   Olá queria informar que o produto não foi entr...
7   Já se passaram quase um mês e nada preciso da ...
8   Falta receber o protetor de porta e os jogos d...
9   Boa tarde. \r\nNão recebo todos os produtos fa...
10    Não estou satisfeita com a qualidade do produto
11  Minha mercadoria não foi entregue , já paguei ...
12                     Aparelho não funciona direito
13  A cor do produto no site é mais claro que o pr...
14  Nao gostei do produto. As toalhas sao muito fi...
15        Comprei duas unidades e recebi apenas uma!
16                          Produto não foi entregue
17  Não foi entregue o produto que solicitei. Entr...
18  Fiquei esperando o produto chegar e nada, most...
19  Difícil de resolver um problema na entrega. Co...

                                      translated_text
0   Product sent Unlike the one in the ad. I asked...
1   Don't buy from this store! I tried to cancel t...
2                                          Excellent.
3   The pool ball game I bought is totally differe...
4                                Bad stuff. unsecured
5   I'd like to know why my product appears as del...
6   Hello I wanted to inform you that the product ...
7   It's been almost a month and I don't need your...
8   Missing to receive door guard and single bed g...
9   Good afternoon.\nI don't get all the products....
10            I am not satisfied with product quality
11  My merchandise wasn't delivered, I already pai...
12                        Apparatus not working right
13  The color of the product on the site is cleare...
14  I don't like the product. The towels are very ...
15               I bought two units and got only one!
16                              Product not delivered
17  The product I requested was not delivered. I'v...
18  I kept waiting for the product to arrive and n...
19  Hard to solve a delivery problem. I bought 3 i...

**Insights** 💡
- Bazı kötü review’lar delivery ile ilgili (`wait_time`, kaçırılan teslim tarihi, vb.)
- Ancak bazı kötü review’lar seller veya ürünle ilgili...

Peki iki olası nedeni nasıl ayırt edebiliriz?

Bu Olist’in mutlaka bilmesi gereken bir şey:
- bazı ürünleri katalogdan mı çıkarmalı?
- yoksa bazı seller’ları marketplace’ten mi kaldırmalı?